# Generated by Django 4.1.5 on 2023-01-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/photos'),
        ),
        migrations.AddField(
            model_name='projects',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos'),
        ),
    ]
