# Generated by Django 4.1.5 on 2023-01-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_datascience_photo_datascience_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='photo',
            field=models.ImageField(blank=True, default='/static/images/default_image.jpg', null=True, upload_to='projects/photos'),
        ),
    ]
